# trials


########

exec-once=waybar
exec-once=swaybg -i ~/wallpapers/wallpaper.jpg
exec-once=wlsunset -S 06:00 -s 17:00 -T 6500 -t 4000

blur=1
blur_layer = 1
blur_optimized = 0
blur_params_num_passes = 2
blur_params_radius = 5

focused_opacity=0.9
unfocused_opacity=0.8

gappih=10
gappiv=10
gappoh=10
gappov=10
borderpx=3

focuscolor = 0xb153a7ff
globalcolor = 0x516c93ff 

xkb_rules_layout=us
xkb_rules_options=caps:swapescape

tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:vertical_scroller

source=./bind.conf
