require("toggleterm").setup({
	size = 20,
	open_mapping = [[<c-h>]],
	hide_numbers = true,
	shade_filetypes = {},
	shade_terminals = true,
	shading_factor = 2,
	start_in_insert = true,
	insert_mappings = true,
	persist_mode = true,
	float_opts = {
		border = "curved",
	},
	terminal_mappings = true,
	persist_size = true,
	autochdir = false,
	direction = "float",
	close_on_exit = true,
	shell = vim.o.shell,
})
